
FROM ubuntu:22.04
WORKDIR /workspace 
RUN apt-get -y update && apt-get install -y && apt-get -y install git tar cmake autoconf automake libtool curl make g++ unzip clang-format 
RUN rm -rf /var/lib/apt/lists/*

